import { useEffect, useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import ChartsSection from './ChartsSection';


interface ChartData {
    direction_chart: {
        data: {
            points: any[];
            allPoints: any[];
            updatedAt: string;
        }
    };
    stats: {
        data: {
            totalSignalsGenerated: number;
            longCount: number;
            shortCount: number;
            flatCount: number;
            updatedAt: string;
        }
    };
}

async function loadChartData(): Promise<ChartData | null> {
    try {
        const res = await fetch(`${import.meta.env.VITE_API_URL}/signals/public/charts`);
        if (!res.ok) return null;
        return await res.json();
    } catch {
        return null;
    }
}

// ── Animated Counter ──────────────────────────────────────────────────────────
function Counter({ to, suffix = '', duration = 1800 }: { to: number; suffix?: string; duration?: number }) {
    const [val, setVal] = useState(0);
    const ref = useRef<boolean>(false);
    useEffect(() => {
        if (ref.current) return;
        ref.current = true;
        const start = Date.now();
        const tick = () => {
            const elapsed = Date.now() - start;
            const progress = Math.min(elapsed / duration, 1);
            const eased = 1 - Math.pow(1 - progress, 3);
            setVal(Math.round(eased * to));
            if (progress < 1) requestAnimationFrame(tick);
        };
        requestAnimationFrame(tick);
    }, [to, duration]);
    return <>{val.toLocaleString()}{suffix}</>;
}

// ── Plan Card ─────────────────────────────────────────────────────────────────
const plans = [
    { name: 'Trial', price: 7, duration: '7 days', calls: 50, rows: 1, note: 'One-time', highlight: false },
    { name: 'Basic', price: 19, duration: '30 days', calls: '1,000', rows: 24, note: '~24 hrs data', highlight: false },
    { name: 'Pro', price: 49, duration: '30 days', calls: '5,000', rows: 48, note: '~48 hrs data', highlight: true },
    { name: 'Enterprise', price: 99, duration: '30 days', calls: 'Unlimited', rows: 72, note: '7 days data', highlight: false },
];

const faqs = [
    { q: 'What exactly does the API return?', a: 'Each API call returns hourly gold (XAU/USD) trade signals — LONG, SHORT, or FLAT — generated by our machine learning model trained on 20+ years of market data. Each signal tells you the predicted direction for that hour.' },
    { q: 'How do I use the signals in my trading?', a: 'Pass the x-api-key header with your key to our endpoint. Your system receives the signal and can act accordingly — enter a LONG position when signal is LONG, SHORT when SHORT, and stay flat otherwise. Adding TP/SL levels can significantly improve returns.' },
    { q: 'What does the backtest show?', a: 'The backtest simulates 30 NY trading days (9:30AM–4:30PM EST) using our signals against actual Yahoo Finance gold OHLC data. It shows the cumulative % return if you followed every signal without any TP/SL. Real trading with proper risk management would perform better.' },
    { q: 'How is payment handled?', a: 'We accept manual bank transfers. After selecting your plan, you submit your transaction reference. Our team verifies and activates your subscription within 24 hours. Stripe/PayPal integration is coming soon.' },
    { q: 'What is the API call limit?', a: 'Each plan has an API call quota. Trial: 50 calls. Basic: 1,000/month. Pro: 5,000/month. Enterprise: unlimited. Each GET request to /signals/gold counts as one call.' },
];

// ── Main Component ────────────────────────────────────────────────────────────
export default function LandingPage() {
    const [chartData, setChartData] = useState<ChartData | null>(null);
    const [openFaq, setOpenFaq] = useState<number | null>(null);
    const [heroVisible, setHeroVisible] = useState(false);
    useEffect(() => {
        loadChartData().then(data => setChartData(data));
    }, []);
    useEffect(() => {
        setTimeout(() => setHeroVisible(true), 100);
    }, []);

    const stats = chartData?.stats?.data;

    return (
        <div style={{ fontFamily: "'EB Garamond', Georgia, serif", background: '#FAF7F2', color: '#1C2B1A', overflowX: 'hidden' }}>

            {/* ── Nav ── */}
            <nav style={{
                position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
                background: 'rgba(28,43,26,0.97)', backdropFilter: 'blur(12px)',
                borderBottom: '1px solid #D4AF6A22',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                padding: '0 48px', height: '60px',
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <img src="/mts-logo.png" alt="mTradingSignal" style={{ width: '32px', height: '32px', objectFit: 'contain' }} />
                    <span style={{ fontFamily: 'Playfair Display, Georgia, serif', color: '#D4AF6A', fontSize: '17px', letterSpacing: '0.04em' }}>
                        mTradingSignal
                    </span>
                </div>
                <div style={{ display: 'flex', gap: '32px', alignItems: 'center' }}>
                    {['Charts', 'Backtest', 'Pricing', 'FAQ'].map(item => (
                        <a key={item} href={`#${item.toLowerCase()}`} style={{ color: '#8aaa84', fontSize: '13px', textDecoration: 'none', letterSpacing: '0.06em', transition: 'color 0.2s' }}
                            onMouseEnter={e => (e.currentTarget.style.color = '#D4AF6A')}
                            onMouseLeave={e => (e.currentTarget.style.color = '#8aaa84')}>
                            {item}
                        </a>
                    ))}
                    <Link to="/login" style={{ color: '#D4AF6A', fontSize: '13px', textDecoration: 'none', border: '1px solid #D4AF6A44', borderRadius: '4px', padding: '6px 16px', letterSpacing: '0.06em' }}>
                        Sign In
                    </Link>
                    <Link to="/register" style={{ background: '#D4AF6A', color: '#1C2B1A', fontSize: '13px', textDecoration: 'none', borderRadius: '4px', padding: '7px 18px', fontWeight: 600, letterSpacing: '0.04em' }}>
                        Get Started
                    </Link>
                </div>
            </nav>

            {/* ── Hero ── */}
            <section style={{
                minHeight: '100vh', background: 'linear-gradient(160deg, #1C2B1A 0%, #2e4029 50%, #1a2518 100%)',
                display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                padding: '120px 48px 80px', textAlign: 'center', position: 'relative', overflow: 'hidden',
            }}>
                {/* Background grain */}
                <div style={{ position: 'absolute', inset: 0, backgroundImage: 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 256 256\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noise\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.9\' numOctaves=\'4\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noise)\' opacity=\'0.04\'/%3E%3C/svg%3E")', opacity: 0.4 }} />

                {/* Decorative gold lines */}
                <div style={{ position: 'absolute', top: '20%', left: '8%', width: '1px', height: '120px', background: 'linear-gradient(to bottom, transparent, #D4AF6A44, transparent)' }} />
                <div style={{ position: 'absolute', top: '30%', right: '10%', width: '1px', height: '80px', background: 'linear-gradient(to bottom, transparent, #D4AF6A33, transparent)' }} />

                <div style={{
                    opacity: heroVisible ? 1 : 0,
                    transform: heroVisible ? 'translateY(0)' : 'translateY(24px)',
                    transition: 'all 0.9s cubic-bezier(0.16, 1, 0.3, 1)',
                }}>
                    <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: '#D4AF6A15', border: '1px solid #D4AF6A33', borderRadius: '20px', padding: '6px 16px', marginBottom: '32px' }}>
                        <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#7ec87e', boxShadow: '0 0 8px #7ec87e' }} />
                        <span style={{ color: '#D4AF6A', fontSize: '12px', letterSpacing: '0.12em' }}>LIVE MODEL · GOLD XAU/USD</span>
                    </div>
                    {/* Injecting the keyframes for the market animation */}
                    <style>
                        {`
                            @keyframes marketVolatility {
                            0% { background-position: 0% 50%; }
                            50% { background-position: 100% 50%; }
                            100% { background-position: 0% 50%; }
                            }
                            .trading-animated-bg {
                            /* Base shifting gradient: Dark Green (Profit) -> Dark/Neutral -> Deep Red (Loss) */
                            background: linear-gradient(
                                -45deg, 
                                #7be26e, /* Dark brand green */
                                #95cb5f, /* Profit green */
                                #c1c1c1, /* Neutral */
                                #da3f3f, /* Loss red */
                                #f10000  /* Back to dark green */
                            );
                            background-size: 400% 400%;
                            animation: marketVolatility 12s ease-in-out infinite;
                            }
                            
                            /* Optional: A subtle grid overlay to make it look like a trading chart */
                            .trading-grid-overlay {
                            position: absolute;
                            top: 0; left: 0; right: 0; bottom: 0;
                            background-image: 
                                linear-gradient(rgba(255, 255, 255, 0.03) 1px, transparent 1px),
                                linear-gradient(90deg, rgba(255, 255, 255, 0.03) 1px, transparent 1px);
                            background-size: 20px 20px;
                            z-index: 0;
                            }
                        `}
                    </style>

                    <div
                        className="trading-animated-bg"
                        style={{
                            minWidth: '250px',
                            alignItems: 'center',
                            justifyContent: 'center',
                            display: 'flex',
                            padding: '24px 12px', /* Slightly padded for better breathing room */
                            borderRadius: '8px',
                            position: 'relative', /* Required to hold the absolute grid and z-index logo */
                            overflow: 'hidden',   /* Keeps the grid inside the rounded corners */
                            boxShadow: 'inset 0 0 20px rgba(0,0,0,0.3)' /* Adds depth */
                        }}
                    >
                        {/* The chart grid overlay */}
                        <div className="trading-grid-overlay"></div>

                        <img
                            src="/mts-logo.png"
                            alt="Brand Logo"
                            style={{
                                maxHeight: '100%',
                                width: '100%',
                                maxWidth: '200px',
                                objectFit: 'contain',
                                position: 'relative',
                                zIndex: 1, /* Ensures the logo sits ABOVE the background animation and grid */
                                filter: 'drop-shadow(0px 4px 6px rgba(0,0,0,0.4))' /* Helps logo pop against moving colors */
                            }}
                        />
                    </div>

                    <h1 style={{
                        fontFamily: 'Playfair Display, Georgia, serif',
                        fontSize: 'clamp(40px, 6vw, 72px)',
                        fontWeight: 400, color: '#FAF7F2',
                        margin: '0 0 8px', lineHeight: 1.1,
                        letterSpacing: '-0.01em',
                    }}>
                        Trade Intelligence
                    </h1>
                    <h1 style={{
                        fontFamily: 'Playfair Display, Georgia, serif',
                        fontSize: 'clamp(40px, 6vw, 72px)',
                        fontWeight: 400, color: '#D4AF6A',
                        margin: '0 0 28px', lineHeight: 1.1,
                        letterSpacing: '-0.01em',
                    }}>
                        Delivered by API
                    </h1>

                    <p style={{ color: '#8aaa84', fontSize: 'clamp(15px, 2vw, 19px)', maxWidth: '560px', margin: '0 auto 40px', lineHeight: 1.7, fontStyle: 'italic' }}>
                        Hourly LONG · SHORT · FLAT signals for XAU/USD, generated by a machine learning model
                        trained on 20+ years of market data. Integrate in minutes.
                    </p>

                    <div style={{ display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap' }}>
                        <Link to="/register" style={{
                            background: '#D4AF6A', color: '#1C2B1A', textDecoration: 'none',
                            padding: '14px 32px', borderRadius: '6px', fontSize: '15px',
                            fontFamily: 'Playfair Display, serif', letterSpacing: '0.04em',
                            boxShadow: '0 4px 20px #D4AF6A33',
                        }}>
                            Start Free Trial →
                        </Link>
                        <a href="#backtest" style={{
                            color: '#D4AF6A', textDecoration: 'none', border: '1px solid #D4AF6A44',
                            padding: '14px 32px', borderRadius: '6px', fontSize: '15px',
                            fontFamily: 'Playfair Display, serif', letterSpacing: '0.04em',
                        }}>
                            View Backtest
                        </a>
                    </div>
                </div>

                {/* Stats bar */}
                {stats && (
                    <div style={{
                        position: 'absolute', bottom: 0, left: 0, right: 0,
                        background: '#D4AF6A0A', borderTop: '1px solid #D4AF6A22',
                        display: 'flex', justifyContent: 'center', gap: '64px',
                        padding: '20px 48px',
                        opacity: heroVisible ? 1 : 0,
                        transition: 'opacity 0.9s ease 0.4s',
                    }}>
                        {[
                            { label: 'Signals Generated', value: stats.totalSignalsGenerated, suffix: '+' },
                            { label: 'LONG Signals', value: stats.longCount, suffix: '' },
                            { label: 'SHORT Signals', value: stats.shortCount, suffix: '' },
                            { label: 'FLAT (No Trade)', value: stats.flatCount, suffix: '' },
                        ].map(({ label, value, suffix }) => (
                            <div key={label} style={{ textAlign: 'center' }}>
                                <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '28px', color: '#D4AF6A', lineHeight: 1 }}>
                                    <Counter to={value} suffix={suffix} />
                                </div>
                                <div style={{ color: '#5C7A58', fontSize: '11px', letterSpacing: '0.1em', marginTop: '4px' }}>{label}</div>
                            </div>
                        ))}
                    </div>
                )}
            </section>

            <ChartsSection
                directionData={chartData?.direction_chart?.data ?? null}
                statsData={chartData?.stats?.data ?? null}
            />

            {/* ── How It Works ── */}
            <section style={{ padding: '100px 48px', background: '#FAF7F2' }}>
                <div style={{ maxWidth: '900px', margin: '0 auto', textAlign: 'center' }}>
                    <div style={{ fontSize: '11px', color: '#8a7e6a', letterSpacing: '0.16em', marginBottom: '12px' }}>PROCESS</div>
                    <h2 style={{ fontFamily: 'Playfair Display, serif', fontSize: '36px', color: '#1C2B1A', fontWeight: 400, marginBottom: '60px' }}>
                        Three Steps to Live Signals
                    </h2>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '40px' }}>
                        {[
                            { step: '01', title: 'Register & Verify', desc: 'Create your account with Gmail. Verify via OTP. Takes under 2 minutes.' },
                            { step: '02', title: 'Choose a Plan', desc: 'Select the subscription that fits your volume. Submit your bank transfer reference.' },
                            { step: '03', title: 'Call the API', desc: 'Use your API key in the x-api-key header. Receive LONG · SHORT · FLAT signals hourly.' },
                        ].map(({ step, title, desc }) => (
                            <div key={step} style={{ textAlign: 'center' }}>
                                <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '48px', color: '#D4AF6A22', marginBottom: '16px', lineHeight: 1 }}>{step}</div>
                                <div style={{ width: '1px', height: '32px', background: 'linear-gradient(to bottom, #D4AF6A33, transparent)', margin: '0 auto 20px' }} />
                                <h3 style={{ fontFamily: 'Playfair Display, serif', fontSize: '19px', color: '#1C2B1A', fontWeight: 400, marginBottom: '10px' }}>{title}</h3>
                                <p style={{ fontSize: '14px', color: '#8a7e6a', fontStyle: 'italic', lineHeight: 1.7 }}>{desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ── Pricing ── */}
            <section id="pricing" style={{ padding: '100px 48px', background: '#1C2B1A' }}>
                <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
                    <div style={{ textAlign: 'center', marginBottom: '60px' }}>
                        <div style={{ fontSize: '11px', color: '#5C7A58', letterSpacing: '0.16em', marginBottom: '12px' }}>PLANS</div>
                        <h2 style={{ fontFamily: 'Playfair Display, serif', fontSize: '36px', color: '#FAF7F2', fontWeight: 400 }}>
                            Subscription Plans
                        </h2>
                        <p style={{ color: '#5C7A58', fontStyle: 'italic', marginTop: '8px' }}>
                            All plans include full API access · Payment via bank transfer · Activated within 24 hours
                        </p>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px' }}>
                        {plans.map(plan => (
                            <div key={plan.name} style={{
                                background: plan.highlight ? '#D4AF6A' : '#2e4029',
                                border: plan.highlight ? 'none' : '1px solid #D4AF6A22',
                                borderRadius: '10px', padding: '28px 20px',
                                position: 'relative', transition: 'transform 0.2s',
                            }}
                                onMouseEnter={e => (e.currentTarget.style.transform = 'translateY(-4px)')}
                                onMouseLeave={e => (e.currentTarget.style.transform = 'translateY(0)')}>
                                {plan.highlight && (
                                    <div style={{ position: 'absolute', top: '-10px', left: '50%', transform: 'translateX(-50%)', background: '#1C2B1A', color: '#D4AF6A', fontSize: '10px', letterSpacing: '0.12em', padding: '3px 12px', borderRadius: '20px', whiteSpace: 'nowrap' }}>
                                        MOST POPULAR
                                    </div>
                                )}
                                <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '20px', color: plan.highlight ? '#1C2B1A' : '#FAF7F2', marginBottom: '4px' }}>{plan.name}</div>
                                <div style={{ fontSize: '11px', color: plan.highlight ? '#2e4029' : '#5C7A58', fontStyle: 'italic', marginBottom: '20px' }}>{plan.note}</div>
                                <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '36px', color: plan.highlight ? '#1C2B1A' : '#D4AF6A', lineHeight: 1, marginBottom: '4px' }}>${plan.price}</div>
                                <div style={{ fontSize: '12px', color: plan.highlight ? '#2e4029' : '#5C7A58', marginBottom: '24px' }}>/ {plan.duration}</div>
                                <div style={{ display: 'flex', flexDirection: 'column' as const, gap: '8px', marginBottom: '24px' }}>
                                    {[
                                        `${typeof plan.calls === 'number' ? plan.calls.toLocaleString() : plan.calls} API calls`,
                                        `${plan.rows} rows per call`,
                                        'LONG · SHORT · FLAT',
                                        'NY market hours',
                                    ].map(feat => (
                                        <div key={feat} style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px', color: plan.highlight ? '#1C2B1A' : '#8aaa84' }}>
                                            <span style={{ color: plan.highlight ? '#2e4029' : '#D4AF6A', fontSize: '10px' }}>✦</span>
                                            {feat}
                                        </div>
                                    ))}
                                </div>
                                <Link to="/register" style={{
                                    display: 'block', textAlign: 'center', textDecoration: 'none',
                                    background: plan.highlight ? '#1C2B1A' : '#D4AF6A15',
                                    color: plan.highlight ? '#D4AF6A' : '#D4AF6A',
                                    border: plan.highlight ? 'none' : '1px solid #D4AF6A33',
                                    borderRadius: '6px', padding: '10px',
                                    fontSize: '13px', fontFamily: 'Playfair Display, serif',
                                    letterSpacing: '0.04em',
                                }}>
                                    Get Started →
                                </Link>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ── FAQ ── */}
            <section id="faq" style={{ padding: '100px 48px', background: '#FAF7F2' }}>
                <div style={{ maxWidth: '720px', margin: '0 auto' }}>
                    <div style={{ textAlign: 'center', marginBottom: '60px' }}>
                        <div style={{ fontSize: '11px', color: '#8a7e6a', letterSpacing: '0.16em', marginBottom: '12px' }}>FAQ</div>

                        <h2 style={{ fontFamily: 'Playfair Display, serif', fontSize: '36px', color: '#1C2B1A', fontWeight: 400 }}>
                            Common Questions
                        </h2>
                    </div>

                    <div style={{ display: 'flex', flexDirection: 'column' as const, gap: '0' }}>
                        {faqs.map((faq, i) => (
                            <div key={i} style={{ borderTop: i === 0 ? '1px solid #DDD6C4' : 'none', borderBottom: '1px solid #DDD6C4' }}>
                                <button
                                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                                    style={{
                                        width: '100%', background: 'none', border: 'none', cursor: 'pointer',
                                        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                                        padding: '20px 0', textAlign: 'left',
                                    }}>
                                    <span style={{ fontFamily: 'Playfair Display, serif', fontSize: '17px', color: '#1C2B1A', fontWeight: 400 }}>{faq.q}</span>
                                    <span style={{ color: '#D4AF6A', fontSize: '20px', transition: 'transform 0.3s', transform: openFaq === i ? 'rotate(45deg)' : 'rotate(0)' }}>+</span>
                                </button>
                                {openFaq === i && (
                                    <div style={{ paddingBottom: '20px' }}>
                                        <p style={{ fontSize: '15px', color: '#8a7e6a', lineHeight: 1.7, fontStyle: 'italic', margin: 0 }}>{faq.a}</p>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ── CTA Banner ── */}
            <section style={{ padding: '80px 48px', background: 'linear-gradient(135deg, #1C2B1A, #2e4029)', textAlign: 'center' }}>
                <div style={{ maxWidth: '600px', margin: '0 auto' }}>
                    <h2 style={{ fontFamily: 'Playfair Display, serif', fontSize: '36px', color: '#FAF7F2', fontWeight: 400, marginBottom: '16px' }}>
                        Start Trading Smarter
                    </h2>
                    <p style={{ color: '#8aaa84', fontStyle: 'italic', fontSize: '16px', marginBottom: '32px', lineHeight: 1.7 }}>
                        Join traders using ML-powered signals. Start with a $7 trial — no commitment required.
                    </p>
                    <Link to="/register" style={{
                        background: '#D4AF6A', color: '#1C2B1A', textDecoration: 'none',
                        padding: '16px 40px', borderRadius: '6px', fontSize: '16px',
                        fontFamily: 'Playfair Display, serif', letterSpacing: '0.04em',
                        boxShadow: '0 4px 24px #D4AF6A44', display: 'inline-block',
                    }}>
                        Begin Free Trial →
                    </Link>
                </div>
            </section>

            {/* ── Footer ── */}
            <footer style={{ background: '#111d10', padding: '40px 48px', borderTop: '1px solid #D4AF6A15' }}>
                <div style={{ maxWidth: '1100px', margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <img src="/mts-logo.png" alt="mTradingSignal" style={{ width: '28px', height: '28px', objectFit: 'contain' }} />
                        <span style={{ fontFamily: 'Playfair Display, serif', color: '#D4AF6A', fontSize: '15px' }}>mTradingSignal</span>
                    </div>
                    <div style={{ display: 'flex', gap: '24px' }}>
                        {['Charts', 'Pricing', 'FAQ'].map(item => (
                            <a key={item} href={`#${item.toLowerCase()}`} style={{ color: '#5C7A58', fontSize: '13px', textDecoration: 'none' }}>{item}</a>
                        ))}
                        <Link to="/login" style={{ color: '#5C7A58', fontSize: '13px', textDecoration: 'none' }}>Sign In</Link>
                    </div>
                    <div style={{ color: '#3a4f38', fontSize: '12px', fontStyle: 'italic' }}>
                        © 2026 mTradingSignal · Not financial advice
                    </div>
                </div>
            </footer>

        </div>
    );
}